<a href="https://colab.research.google.com/github/Ararine/Ararine.github.io/blob/master/python_11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### (6) 3차원 이상에서 차원 구분법

In [1]:
import numpy as np

In [2]:
# 0부터 24미만 까지 생성
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분 가능
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(b[0])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(b[1])

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(b[0,1])

[4 5 6 7]


In [ ]:
print(b[1,1])

[16 17 18 19]


In [ ]:
b[0,1,3]

7

### (7) fancy indexing와 indexing의 차이
  - indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [ ]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원 2차원으로 가져온다.)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b[0]은 b[0,:,:]의 단축 표현이다.
b[[0],:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b의 0번째 공간, 1번째 행 미만, 열전체
b[0,:1,:]


array([[0, 1, 2, 3]])

### (8) Ellipsis
  - ...(Ellipsis)은 이후로 모든 것을 의미한다.

In [ ]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
type(...)

ellipsis

In [ ]:
b[0] # 생략기법
b[0,:,:] # slicing 기법
b[0,...] # Ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 숫자 1, 5, 9만 가져온다.
b[0,:,1]

array([1, 5, 9])

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 숫자 1,5,9,3,7,11 가져오기
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [6]:
# 숫자 4, 5, 6, 7, 16, 17, 18, 19 가져오기
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [8]:
b[:,1:2,:]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [13]:
# 3, 7, 11, 15, 19, 23 가져오기
b[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [16]:
b[:,:,3:4]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [18]:
b[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [25]:
b[:,:,-1:]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [26]:
b[:,:,[3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [28]:
c = b[:,:,3]
c.shape

(2, 3)

In [31]:
d = b[:,:,3:]
d.shape

(2, 3, 1)

In [32]:
b[...,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

#### 줄임표현(...)
  - 출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Ellipsis와 다르다.

In [30]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

- 출력될 개수를 설정하기
- (np.set_printoptions(edgeitem=?)

In [33]:
np.set_printoptions(edgeitems=6)

In [34]:
np.arange(1000000)

array([     0,      1,      2,      3,      4,      5, ..., 999994,
       999995, 999996, 999997, 999998, 999999])

### (9) 연산
- numpy연산의 기본은 두개의 shape이 같아야 한다.

In [35]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a.shape

(3, 4)

In [37]:
b = np.arange(1, 13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
b.shape

(3, 4)

- numpy는 elementwise로 vectorize 연산을 한다.
- vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [39]:
# 같은 위치의 원소끼리 더해준다. (elementwise)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [40]:
# python의 list에서 + 연산자는 elementwise가 아니라 list를 확장시킨다. (연결)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

- numpy는 python함수로 vectorize 시키는 기능을 지원한다.

In [43]:
@np.vectorize 
def plus(a,b):
  return a+b

plus([1,2,3],[4,5,6]) # elementwise, vectorize

array([5, 7, 9])

In [45]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
b = np.arange(6, 12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
a * b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [49]:
# python의 list끼리 * (곱하기)를 할 수 없다.
[1,2,3] * [4,5,6]

TypeError: ignored

In [50]:
type(np.array(3))

numpy.ndarray

In [51]:

c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [52]:
type(c)

numpy.matrix

- numpy에서는 ndarray 이외에 matrix라는 자료형도 존재한다.
- matrix에서는 * 연산자는 행렬곱을 의미한다.

In [53]:
# matrix * matrix = 행렬곱
# [1*1+2*3],[1*2+2*4]
# [3*1+4*3],[3*2+4*4]
c * c

matrix([[ 7, 10],
        [15, 22]])

- ndarray에서 행렬곱 연산자는 @이다.
- python재단에서 numpy를 위해 만들어준 연산자이다.

In [54]:
a.shape

(2, 3)

In [56]:
b.shape

(2, 3)

In [57]:
a @ b

ValueError: ignored

- 행렬곱을 하기 위해서는 shape가 맞아야 한다.
- T는 transpose(전치)의 약자이다.

In [58]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
# 전치 행렬 : 행과 열을 바꾼다.
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [60]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

- matrix는 @와 * 모두 행렬 곱의 연산자로 사용이 가능하다.

In [61]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [62]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

- 함수방법으로 np.dot()을 사용할 수 있다. (행렬곱)

In [63]:
np.dot(a, a.T) #ndarray

array([[ 5, 14],
       [14, 50]])

In [64]:
np.dot(c, c.T)

matrix([[ 5, 11],
        [11, 25]])

- method 방법으로도 행렬곱 할 수 있다.
- function 방법과 사용하는 방법이 다르므로 주의한다.

In [65]:
np.dot(a, a.T) # function 방식

array([[ 5, 14],
       [14, 50]])

In [66]:
a.dot(a.T) # 메소드 방식

array([[ 5, 14],
       [14, 50]])

- 행렬 곱을 하는 방법 정리

1. ndarray @
2. matrix @, *
3. np.dot() function
4. a.dot() method

### (10) broadcasting
- python은 배열과 숫자간에 연산을 할 수 있다.

In [67]:
[1,2,3] + 1

TypeError: ignored

- [1,2,3] + 1       - X  
- [1,2,3] + [1,2,3] - O => 연결  
- [1,2,3] * 1       - O => 반복  
- [1,2,3] * [1,2,3] - X  

In [68]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

- broadcasting이란 모양(shape)이 안 맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.
- 위 연산에서 1을 a와 같은 모양으로 만들어 준다.  
[[1,1,1],  
 [1,1,1]]

#### (1)broadcasting이 안되는 경우와 가능한 경우

In [70]:
a # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
a + np.array([3,4])

ValueError: ignored

In [72]:
a + np.array([3,4,5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [73]:
a + np.array([[1],[2]])

array([[1, 2, 3],
       [5, 6, 7]])

- 스칼라 값일 경우 값을 복사해서 연산하는 행열과 같게 만들어줘서 연산이 가능해진다.
- 스칼라 값이 아닌 행렬의 경우 행이 같거나 열이 같으면 그 값을 복사해서 만들어주기 때문에 연산이 가능해진다.

### (11) strides
- strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.
- c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [74]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
# 행의 메모리 간격은 32bytes
# 열의 메모리 간격은 8bytes
a.strides

(32, 8)

In [77]:
a.dtype

dtype('int64')

In [78]:
a.itemsize

8

In [79]:
# 열의 원소개수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

### 12 axis
- axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
np.sum(a)

66

In [83]:
np.sum(a, axis=0) # a배열은 2차원이므로 axis = 0은 행기준(행마다)

array([12, 15, 18, 21])

In [84]:
np.sum(a, axis = 1) # a배열은 2차원이므로 axis = 1은 열기준(열마다)

array([ 6, 22, 38])

(0,0), (0,1), (0,2), (0,3)  
(1,0), (1,1), (1,2), (1,3)  
(2,0), (2,1), (2,2), (2,3)  
- 변하는 값이 기준

- axis는 3차원 이상에서도 사용할 수 있다.

In [85]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(0,0,0)(0,0,1)(0,0,2)(0,0,3)  
(0,1,0)(0,1,1)(0,1,2)(0,1,3)  
(0,2,0)(0,2,1)(0,2,2)(0,2,3)  
  
(1,0,0)(1,0,1)(1,0,2)(1,0,3)  
(1,1,0)(1,1,1)(1,1,2)(1,1,3)  
(1,2,0)(1,2,1)(1,2,2)(1,2,3)  

In [86]:
# a.sum(axix=0)
np.sum(a, axis=0) # 공간기준 (공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [89]:
# a.sum(axis=1)
np.sum(a, axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [90]:
# a.sum(axis=2)
np.sum(a, axis=2) # 열기준(열마다)

array([[ 6, 22, 38],
       [54, 70, 86]])

- 3차원은 행렬에 공간(깊이) 개념이 추가되었다고 할 수 있다.
- 2차원(axis = 0, axis = 1)(행,열)
- 3차월(axis = 0. axis =1, axis = 2)(공간,행,열)

### (12) array 모양 바꾸기

(1) reshape
- reshape은 차원을 바꿔주는 기능을 한다.

In [95]:
# signature대로 하면 a.reshape((3,8))로 해야한다.
# 하지만 reshape(3,8)해도 내부적으로 이상없이 처리한다.
# reshape 수행 후의 원본의 값은 수행 전의 값과 같다.
a = np.arange(24)
b = a.reshape(3,8)

print(a)
print('='*100)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [97]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [98]:
# ValueError = > 크기가 맞지 않음
a.reshape(2,3,5)

ValueError: ignored

In [99]:
# 음수를 쓰면, 알아서 shape을 맞춘다.
a.reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [100]:
# 음수이기만 하면 -100도 상관없다.
a.reshape(2,3,-100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [101]:
# 1,2 번째 인수의 곱이 배열의 약수이어야만 한다.
a.reshape(3,5,-1)

ValueError: ignored

In [102]:
# 음수의 값은 하나만 사용이 가능하다. (두 개 X)
# 음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3, -1, -1)

ValueError: ignored

In [103]:
# 음수값이 1개이면 어느 위치에 오든 상관없다.
a.reshape(3,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

- (2) reshape으로 차원 늘리기

In [105]:
# 2차원
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
# 3차원
a = np.arange(6).reshape(2,3,1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

### (13) resize
- size는 원소 개수를 알려준다.

In [108]:
a = np.arange(24)
# 원소의 개수
print(a.size)
print(len(a))

24
24


In [112]:
# a.resize(2,3,1)
np.resize(a, (2,3,1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [118]:
# 빈 공간은 반복으로 채워줌
np.resize(a, (3,2,8))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [125]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape과 차이점 1
# 원래의 원소 개수와 변경하는 원소 개수가 안 맞아도 된다. (0으로 채워준다) -> reshape과 차이점 2
b = np.arange(24)
b.resize(2,3,8)
print(b)

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]]

 [[ 0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0]]]


### array 쪼개기


- split

In [141]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [143]:
# a는 바뀌지 않으므로 재할당을 한다.
a = np.split(a, 3, axis=0)
a

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [140]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [145]:
b = np.arange(24)
b = np.split(b,2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [151]:
print(type(b))
print(type(b[1]))
print(b[1])
print(b[1][2])
# print(b[1,2]) # TypeError => array

c = np.array(b)
print(c)
print(type(c))
print(c[1,2])

<class 'list'>
<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23]
14
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>
14


#### hsplit & vsplit

- split은 axis 파라미터가 있다. default : axis = 0

In [152]:
a = np.arange(24)
b = a.reshape(4,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [153]:
np.split(b, 2, axis = 0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [154]:
np.split(b, 2, axis = 1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [155]:
np.hsplit(a, 2) # horizental(수평)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [156]:
# vsplit은 1차원일 때 ValueError가 발생한다.
np.vsplit(b, 2) # 2차원일때 : Vertical(수직)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [157]:
np.hsplit(b,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

(0,0), (0,1), (0,2), (0,3), (0,4)  
(1,0), (1,1), (1,2), (1,3), (1,4)  
(2,0), (2,1), (2,2), (2,3), (2,4)  
(3,0), (3,1), (3,2), (3,3), (3,4)  

#### indices_or_sections
- split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_sections이다.
- 숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [160]:
a = np.arange(24)

In [162]:
# section
# 처음부터 ~ 2미만 : [0,1]
# 2부터 ~ 3미만 : [2]
# 3부터 ~ 끝까지 : [3,...,23]
np.hsplit(a, (2,3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [163]:
# section
# 처음부터 ~ 2미만 : [0,1]
# 2부터 ~ 3미만 : [2]
# 3부터 ~ 8미만 : [3,...,7]
# 8부터 ~ 끝까지 : [8,...,23]
np.hsplit(a,(2,3,8))

[array([0, 1]),
 array([2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

#### (14) array 합치기

In [164]:
a = np.arange(24)
x, y, z = np.split(a, 3)

In [165]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


#### hstack & vstack


In [166]:
# hstack은 horizental(가로)로 합쳐준다.
np.hstack((x,y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [167]:
# vstack은 vertical(세로)로 합쳐준다.
np.vstack((x,y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

#### dstack
- dstack은 합쳐서 3차원으로 만들어 준다.
- 합칠 array들이 1차원, 2차원일 경우는 차원을 늘린 후 합친다.
- 합쳐지는 차원은 axis=2이다.

In [168]:
print(x)
print(y)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [172]:
# x는 shape 1차원 이므로 (1, m, 1)인 차원으로 변환한다.
# y는 shape 1차원 이므로 (1, n, 1)
# 합쳐지는 차원은 axis=2 이다.
c = np.dstack((x,y)) # (1,8,2)
print(c)
d = np.dstack(x)
print(d)

[[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]
  [ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]]
[[[0 1 2 3 4 5 6 7]]]


In [173]:
# x.shape
c.shape

(1, 8, 2)

#### concatenate
- concatenate는 axis 방향에 그대로 합쳐준다.
- ※ stack는 axis 방향에 새로운 차원을 만들어 합쳐준다.

In [174]:
a = np.arange(12).reshape(3,4)
x, y = np.split(a, 2, axis = 1)

In [178]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [177]:
# 원래 shape 크기 그대로 유지를 한다.
np.concatenate((x,y)) # axis = 0

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [179]:
# shape 크기를 1개 증가해서 합친다.
np.stack((x,y))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

### (15) 차원 확장
- numpy는 차원을 확장하는 여러가지 방법이 있다.

- reshape

In [180]:
# np.arange(12) : 1차원
# reshape(3,4) : 2차원
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- stack

In [184]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장시켜 준다.
np.stack((a,))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

- newaxis
  - 인덱싱할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [185]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
#a[np.newaxis]
a[np.newaxis, :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [189]:
a[np.newaxis].shape

(1, 3, 4)

In [191]:
a[:,np.newaxis,:]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [193]:
a[:,np.newaxis,:].shape

(3, 1, 4)

In [194]:
a[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [195]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [196]:
np.newaxis is None

True

- np.newaxis 대신에 None을 써도 된다.
- None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.
- numpy를 만들 때 python의 모든 연산자를 다 사용해서 남는 연산자가 없었다.
- 그래서 None을 이용했다.

In [198]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### expand_dims

In [199]:
np.expand_dims(a, 0) # a[np.newaxis, :, :] 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [200]:
a[np.newaxis, :, :] #[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [201]:
np.expand_dims(a, 1) # a[:,np.newaxis, :]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [202]:
a[:, np.newaxis]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [203]:
np.expand_dims(a, 2) # a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [204]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### (16) array 한줄로 펴기

- flatten

In [205]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
# flatten()은 결과를 return하고 메모리의 값은 변경되지 않는다.
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### (17) 서로 차원 교환

swapaxes

In [208]:
a = np.array([[1],[2]]) # 2차원 2행 1열
a

array([[1],
       [2]])

In [209]:
a.shape

(2, 1)

In [210]:
# a의 0번 차원과 1번 차원을 서로 바꾼다.
b = np.swapaxes(a, 1, 0)
b

array([[1, 2]])

In [211]:
a.T

array([[1, 2]])